
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTER_H
#define MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data Master_Data;
extern UNS16 passageway_detector_cps_left_1_low;		/* Mapped at index 0x2000, subindex 0x01 */
extern UNS16 passageway_detector_cps_left_1_high;		/* Mapped at index 0x2000, subindex 0x02 */
extern UNS16 passageway_detector_cps_right_1_low;		/* Mapped at index 0x2000, subindex 0x03 */
extern UNS16 passageway_detector_cps_right_1_high;		/* Mapped at index 0x2000, subindex 0x04 */
extern UNS16 passageway_detector_cps_left_2_low;		/* Mapped at index 0x2000, subindex 0x05 */
extern UNS16 passageway_detector_cps_left_2_high;		/* Mapped at index 0x2000, subindex 0x06 */
extern UNS16 passageway_detector_cps_right_2_low;		/* Mapped at index 0x2000, subindex 0x07 */
extern UNS16 passageway_detector_cps_right_2_high;		/* Mapped at index 0x2000, subindex 0x08 */
extern UNS16 passageway_detector_cps_left_3_low;		/* Mapped at index 0x2000, subindex 0x09 */
extern UNS16 passageway_detector_cps_left_3_high;		/* Mapped at index 0x2000, subindex 0x0A */
extern UNS16 passageway_detector_cps_right_3_low;		/* Mapped at index 0x2000, subindex 0x0B */
extern UNS16 passageway_detector_cps_right_3_high;		/* Mapped at index 0x2000, subindex 0x0C */
extern UNS16 passageway_detector_cps_left_4_low;		/* Mapped at index 0x2000, subindex 0x0D */
extern UNS16 passageway_detector_cps_left_4_high;		/* Mapped at index 0x2000, subindex 0x0E */
extern UNS16 passageway_detector_cps_right_4_low;		/* Mapped at index 0x2000, subindex 0x0F */
extern UNS16 passageway_detector_cps_right_4_high;		/* Mapped at index 0x2000, subindex 0x10 */
extern UNS8 passageway_alarm_data_channel_left;		/* Mapped at index 0x2001, subindex 0x01 */
extern UNS8 passageway_alarm_data_channel_right;		/* Mapped at index 0x2001, subindex 0x02 */
extern UNS16 passageway_alarm_data_monitor_speed;		/* Mapped at index 0x2001, subindex 0x03 */
extern UNS8 passageway_fault_data_channel_left;		/* Mapped at index 0x2002, subindex 0x01 */
extern UNS8 passageway_fault_data_channel_right;		/* Mapped at index 0x2002, subindex 0x02 */
extern UNS8 passageway_status_data_work;		/* Mapped at index 0x2003, subindex 0x01 */
extern UNS8 passageway_status_data_monitor;		/* Mapped at index 0x2003, subindex 0x02 */
extern UNS8 passageway_status_data_preheat_left;		/* Mapped at index 0x2003, subindex 0x03 */
extern UNS8 passageway_status_data_preheat_right;		/* Mapped at index 0x2003, subindex 0x04 */
extern UNS16 passageway_parameter_type_modbus_id;		/* Mapped at index 0x2004, subindex 0x01 */
extern UNS32 passageway_parameter_factory_year_serial_number;		/* Mapped at index 0x2004, subindex 0x02 */
extern UNS8 test_1_test_1_1;		/* Mapped at index 0x2005, subindex 0x01 */
extern UNS8 test_1_test_1_2;		/* Mapped at index 0x2005, subindex 0x02 */
extern UNS8 test_1_test_1_3;		/* Mapped at index 0x2005, subindex 0x03 */
extern UNS8 test_1_test_1_4;		/* Mapped at index 0x2005, subindex 0x04 */
extern UNS8 test_2_test_2_1;		/* Mapped at index 0x2006, subindex 0x01 */
extern UNS8 test_2_test_2_2;		/* Mapped at index 0x2006, subindex 0x02 */
extern UNS8 test_2_test_2_3;		/* Mapped at index 0x2006, subindex 0x03 */
extern UNS8 test_2_test_2_4;		/* Mapped at index 0x2006, subindex 0x04 */
extern UNS8 test_3_test_3_1;		/* Mapped at index 0x2007, subindex 0x01 */
extern UNS8 test_3_test_3_2;		/* Mapped at index 0x2007, subindex 0x02 */
extern UNS8 test_3_test_3_3;		/* Mapped at index 0x2007, subindex 0x03 */
extern UNS8 test_3_test_3_4;		/* Mapped at index 0x2007, subindex 0x04 */
extern UNS8 test_4_test_4_1;		/* Mapped at index 0x2008, subindex 0x01 */
extern UNS8 test_4_test_4_2;		/* Mapped at index 0x2008, subindex 0x02 */
extern UNS8 test_4_test_4_3;		/* Mapped at index 0x2008, subindex 0x03 */
extern UNS8 test_4_test_4_4;		/* Mapped at index 0x2008, subindex 0x04 */

#endif // MASTER_H
