
/* File generated by gen_cfile.py. Should not be modified. */

#include "Master.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 passageway_detector_cps_left_1_low = 0x0;		/* Mapped at index 0x2000, subindex 0x01 */
UNS16 passageway_detector_cps_left_1_high = 0x0;		/* Mapped at index 0x2000, subindex 0x02 */
UNS16 passageway_detector_cps_right_1_low = 0x0;		/* Mapped at index 0x2000, subindex 0x03 */
UNS16 passageway_detector_cps_right_1_high = 0x0;		/* Mapped at index 0x2000, subindex 0x04 */
UNS16 passageway_detector_cps_left_2_low = 0x0;		/* Mapped at index 0x2000, subindex 0x05 */
UNS16 passageway_detector_cps_left_2_high = 0x0;		/* Mapped at index 0x2000, subindex 0x06 */
UNS16 passageway_detector_cps_right_2_low = 0x0;		/* Mapped at index 0x2000, subindex 0x07 */
UNS16 passageway_detector_cps_right_2_high = 0x0;		/* Mapped at index 0x2000, subindex 0x08 */
UNS16 passageway_detector_cps_left_3_low = 0x0;		/* Mapped at index 0x2000, subindex 0x09 */
UNS16 passageway_detector_cps_left_3_high = 0x0;		/* Mapped at index 0x2000, subindex 0x0A */
UNS16 passageway_detector_cps_right_3_low = 0x0;		/* Mapped at index 0x2000, subindex 0x0B */
UNS16 passageway_detector_cps_right_3_high = 0x0;		/* Mapped at index 0x2000, subindex 0x0C */
UNS16 passageway_detector_cps_left_4_low = 0x0;		/* Mapped at index 0x2000, subindex 0x0D */
UNS16 passageway_detector_cps_left_4_high = 0x0;		/* Mapped at index 0x2000, subindex 0x0E */
UNS16 passageway_detector_cps_right_4_low = 0x0;		/* Mapped at index 0x2000, subindex 0x0F */
UNS16 passageway_detector_cps_right_4_high = 0x0;		/* Mapped at index 0x2000, subindex 0x10 */
UNS8 passageway_alarm_data_channel_left = 0x0;		/* Mapped at index 0x2001, subindex 0x01 */
UNS8 passageway_alarm_data_channel_right = 0x0;		/* Mapped at index 0x2001, subindex 0x02 */
UNS16 passageway_alarm_data_monitor_speed = 0x0;		/* Mapped at index 0x2001, subindex 0x03 */
UNS8 passageway_fault_data_channel_left = 0x0;		/* Mapped at index 0x2002, subindex 0x01 */
UNS8 passageway_fault_data_channel_right = 0x0;		/* Mapped at index 0x2002, subindex 0x02 */
UNS8 passageway_status_data_work = 0x0;		/* Mapped at index 0x2003, subindex 0x01 */
UNS8 passageway_status_data_monitor = 0x0;		/* Mapped at index 0x2003, subindex 0x02 */
UNS8 passageway_status_data_preheat_left = 0x0;		/* Mapped at index 0x2003, subindex 0x03 */
UNS8 passageway_status_data_preheat_right = 0x0;		/* Mapped at index 0x2003, subindex 0x04 */
UNS16 passageway_parameter_type_modbus_id = 0x0;		/* Mapped at index 0x2004, subindex 0x01 */
UNS32 passageway_parameter_factory_year_serial_number = 0x0;		/* Mapped at index 0x2004, subindex 0x02 */
UNS8 test_1_test_1_1 = 0x0;		/* Mapped at index 0x2005, subindex 0x01 */
UNS8 test_1_test_1_2 = 0x0;		/* Mapped at index 0x2005, subindex 0x02 */
UNS8 test_1_test_1_3 = 0x0;		/* Mapped at index 0x2005, subindex 0x03 */
UNS8 test_1_test_1_4 = 0x0;		/* Mapped at index 0x2005, subindex 0x04 */
UNS8 test_2_test_2_1 = 0x0;		/* Mapped at index 0x2006, subindex 0x01 */
UNS8 test_2_test_2_2 = 0x0;		/* Mapped at index 0x2006, subindex 0x02 */
UNS8 test_2_test_2_3 = 0x0;		/* Mapped at index 0x2006, subindex 0x03 */
UNS8 test_2_test_2_4 = 0x0;		/* Mapped at index 0x2006, subindex 0x04 */
UNS8 test_3_test_3_1 = 0x0;		/* Mapped at index 0x2007, subindex 0x01 */
UNS8 test_3_test_3_2 = 0x0;		/* Mapped at index 0x2007, subindex 0x02 */
UNS8 test_3_test_3_3 = 0x0;		/* Mapped at index 0x2007, subindex 0x03 */
UNS8 test_3_test_3_4 = 0x0;		/* Mapped at index 0x2007, subindex 0x04 */
UNS8 test_4_test_4_1 = 0x0;		/* Mapped at index 0x2008, subindex 0x01 */
UNS8 test_4_test_4_2 = 0x0;		/* Mapped at index 0x2008, subindex 0x02 */
UNS8 test_4_test_4_3 = 0x0;		/* Mapped at index 0x2008, subindex 0x03 */
UNS8 test_4_test_4_4 = 0x0;		/* Mapped at index 0x2008, subindex 0x04 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Master_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Master_iam_a_slave = 0;

TIMER_HANDLE Master_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Master_obj1000 = 0x0;	/* 0 */
                    subindex Master_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Master_obj1001 = 0x0;	/* 0 */
                    subindex Master_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Master_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t Master_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex Master_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 Master_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 Master_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 Master_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 Master_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 Master_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 Master_highestSubIndex_obj1016 = 0;
                    UNS32 Master_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 Master_obj1017 = 0x0;	/* 0 */
                    ODCallback_t Master_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex Master_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 Master_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex Master_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Serial_Number }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 Master_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 Master_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex Master_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1400_COB_ID_used_by_PDO = 0x181;	/* 385 */
                    UNS8 Master_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 Master_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1401_COB_ID_used_by_PDO = 0x281;	/* 641 */
                    UNS8 Master_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 Master_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1402_COB_ID_used_by_PDO = 0x381;	/* 897 */
                    UNS8 Master_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 Master_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1403_COB_ID_used_by_PDO = 0x481;	/* 1153 */
                    UNS8 Master_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1403_SYNC_start_value }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 Master_highestSubIndex_obj1404 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1404_COB_ID_used_by_PDO = 0x186;	/* 390 */
                    UNS8 Master_obj1404_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1404_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1404_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1404_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1404_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1404[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1404 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1404_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1404_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1404_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1404_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1404_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1404_SYNC_start_value }
                     };

/* index 0x1405 :   Receive PDO 6 Parameter. */
                    UNS8 Master_highestSubIndex_obj1405 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1405_COB_ID_used_by_PDO = 0x286;	/* 646 */
                    UNS8 Master_obj1405_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1405_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1405_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1405_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1405_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1405[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1405 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1405_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1405_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1405_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1405_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1405_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1405_SYNC_start_value }
                     };

/* index 0x1406 :   Receive PDO 7 Parameter. */
                    UNS8 Master_highestSubIndex_obj1406 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1406_COB_ID_used_by_PDO = 0x386;	/* 902 */
                    UNS8 Master_obj1406_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1406_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1406_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1406_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1406_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1406[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1406 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1406_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1406_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1406_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1406_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1406_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1406_SYNC_start_value }
                     };

/* index 0x1407 :   Receive PDO 8 Parameter. */
                    UNS8 Master_highestSubIndex_obj1407 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1407_COB_ID_used_by_PDO = 0x182;	/* 386 */
                    UNS8 Master_obj1407_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1407_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1407_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1407_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1407_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1407[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1407 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1407_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1407_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1407_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1407_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1407_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1407_SYNC_start_value }
                     };

/* index 0x1408 :   Receive PDO 9 Parameter. */
                    UNS8 Master_highestSubIndex_obj1408 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1408_COB_ID_used_by_PDO = 0x282;	/* 642 */
                    UNS8 Master_obj1408_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1408_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1408_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1408_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1408_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1408[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1408 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1408_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1408_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1408_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1408_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1408_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1408_SYNC_start_value }
                     };

/* index 0x1409 :   Receive PDO 10 Parameter. */
                    UNS8 Master_highestSubIndex_obj1409 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1409_COB_ID_used_by_PDO = 0x382;	/* 898 */
                    UNS8 Master_obj1409_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1409_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1409_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1409_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1409_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1409[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1409 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1409_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1409_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1409_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1409_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1409_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1409_SYNC_start_value }
                     };

/* index 0x140A :   Receive PDO 11 Parameter. */
                    UNS8 Master_highestSubIndex_obj140A = 6; /* number of subindex - 1*/
                    UNS32 Master_obj140A_COB_ID_used_by_PDO = 0x482;	/* 1154 */
                    UNS8 Master_obj140A_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj140A_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj140A_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj140A_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj140A_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index140A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj140A },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj140A_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj140A_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj140A_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj140A_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj140A_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj140A_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Master_highestSubIndex_obj1600 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1600[] = 
                    {
                      0x20000110,	/* 536871184 */
                      0x20000210,	/* 536871440 */
                      0x20000310,	/* 536871696 */
                      0x20000410	/* 536871952 */
                    };
                    subindex Master_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[3] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 Master_highestSubIndex_obj1601 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1601[] = 
                    {
                      0x20000510,	/* 536872208 */
                      0x20000610,	/* 536872464 */
                      0x20000710,	/* 536872720 */
                      0x20000810	/* 536872976 */
                    };
                    subindex Master_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[3] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 Master_highestSubIndex_obj1602 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1602[] = 
                    {
                      0x20000910,	/* 536873232 */
                      0x20000A10,	/* 536873488 */
                      0x20000B10,	/* 536873744 */
                      0x20000C10	/* 536874000 */
                    };
                    subindex Master_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1602[3] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 Master_highestSubIndex_obj1603 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1603[] = 
                    {
                      0x20000D10,	/* 536874256 */
                      0x20000E10,	/* 536874512 */
                      0x20000F10,	/* 536874768 */
                      0x20001010	/* 536875024 */
                    };
                    subindex Master_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[3] }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 Master_highestSubIndex_obj1604 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1604[] = 
                    {
                      0x20010108,	/* 536936712 */
                      0x20010208,	/* 536936968 */
                      0x20010310	/* 536937232 */
                    };
                    subindex Master_Index1604[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1604 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1604[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1604[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1604[2] }
                     };

/* index 0x1605 :   Receive PDO 6 Mapping. */
                    UNS8 Master_highestSubIndex_obj1605 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1605[] = 
                    {
                      0x20020108,	/* 537002248 */
                      0x20020208	/* 537002504 */
                    };
                    subindex Master_Index1605[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1605 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1605[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1605[1] }
                     };

/* index 0x1606 :   Receive PDO 7 Mapping. */
                    UNS8 Master_highestSubIndex_obj1606 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1606[] = 
                    {
                      0x20030108,	/* 537067784 */
                      0x20030208,	/* 537068040 */
                      0x20030308,	/* 537068296 */
                      0x20030408	/* 537068552 */
                    };
                    subindex Master_Index1606[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1606 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1606[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1606[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1606[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1606[3] }
                     };

/* index 0x1607 :   Receive PDO 8 Mapping. */
                    UNS8 Master_highestSubIndex_obj1607 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1607[] = 
                    {
                      0x20050108,	/* 537198856 */
                      0x20050208,	/* 537199112 */
                      0x20050308,	/* 537199368 */
                      0x20050408	/* 537199624 */
                    };
                    subindex Master_Index1607[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1607 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1607[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1607[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1607[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1607[3] }
                     };

/* index 0x1608 :   Receive PDO 9 Mapping. */
                    UNS8 Master_highestSubIndex_obj1608 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1608[] = 
                    {
                      0x20060108,	/* 537264392 */
                      0x20060208,	/* 537264648 */
                      0x20060308,	/* 537264904 */
                      0x20060408	/* 537265160 */
                    };
                    subindex Master_Index1608[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1608 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1608[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1608[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1608[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1608[3] }
                     };

/* index 0x1609 :   Receive PDO 10 Mapping. */
                    UNS8 Master_highestSubIndex_obj1609 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1609[] = 
                    {
                      0x20070108,	/* 537329928 */
                      0x20070208,	/* 537330184 */
                      0x20070308,	/* 537330440 */
                      0x20070408	/* 537330696 */
                    };
                    subindex Master_Index1609[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1609 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1609[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1609[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1609[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1609[3] }
                     };

/* index 0x160A :   Receive PDO 11 Mapping. */
                    UNS8 Master_highestSubIndex_obj160A = 4; /* number of subindex - 1*/
                    UNS32 Master_obj160A[] = 
                    {
                      0x20080108,	/* 537395464 */
                      0x20080208,	/* 537395720 */
                      0x20080308,	/* 537395976 */
                      0x20080408	/* 537396232 */
                    };
                    subindex Master_Index160A[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj160A },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj160A[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj160A[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj160A[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj160A[3] }
                     };

/* index 0x2000 :   Mapped variable passageway_detector_cps */
                    UNS8 Master_highestSubIndex_obj2000 = 16; /* number of subindex - 1*/
                    subindex Master_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2000 },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_detector_cps_left_1_low },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_detector_cps_left_1_high },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_detector_cps_right_1_low },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_detector_cps_right_1_high },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_detector_cps_left_2_low },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_detector_cps_left_2_high },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_detector_cps_right_2_low },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_detector_cps_right_2_high },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_detector_cps_left_3_low },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_detector_cps_left_3_high },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_detector_cps_right_3_low },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_detector_cps_right_3_high },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_detector_cps_left_4_low },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_detector_cps_left_4_high },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_detector_cps_right_4_low },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_detector_cps_right_4_high }
                     };

/* index 0x2001 :   Mapped variable passageway_alarm_data */
                    UNS8 Master_highestSubIndex_obj2001 = 3; /* number of subindex - 1*/
                    subindex Master_Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2001 },
                       { RW, uint8, sizeof (UNS8), (void*)&passageway_alarm_data_channel_left },
                       { RW, uint8, sizeof (UNS8), (void*)&passageway_alarm_data_channel_right },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_alarm_data_monitor_speed }
                     };

/* index 0x2002 :   Mapped variable passageway_fault_data */
                    UNS8 Master_highestSubIndex_obj2002 = 2; /* number of subindex - 1*/
                    subindex Master_Index2002[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2002 },
                       { RW, uint8, sizeof (UNS8), (void*)&passageway_fault_data_channel_left },
                       { RW, uint8, sizeof (UNS8), (void*)&passageway_fault_data_channel_right }
                     };

/* index 0x2003 :   Mapped variable passageway_status_data */
                    UNS8 Master_highestSubIndex_obj2003 = 4; /* number of subindex - 1*/
                    subindex Master_Index2003[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2003 },
                       { RW, uint8, sizeof (UNS8), (void*)&passageway_status_data_work },
                       { RW, uint8, sizeof (UNS8), (void*)&passageway_status_data_monitor },
                       { RW, uint8, sizeof (UNS8), (void*)&passageway_status_data_preheat_left },
                       { RW, uint8, sizeof (UNS8), (void*)&passageway_status_data_preheat_right }
                     };

/* index 0x2004 :   Mapped variable passageway_parameter */
                    UNS8 Master_highestSubIndex_obj2004 = 2; /* number of subindex - 1*/
                    subindex Master_Index2004[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2004 },
                       { RW, uint16, sizeof (UNS16), (void*)&passageway_parameter_type_modbus_id },
                       { RW, uint32, sizeof (UNS32), (void*)&passageway_parameter_factory_year_serial_number }
                     };

/* index 0x2005 :   Mapped variable test_1 */
                    UNS8 Master_highestSubIndex_obj2005 = 4; /* number of subindex - 1*/
                    subindex Master_Index2005[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2005 },
                       { RW, uint8, sizeof (UNS8), (void*)&test_1_test_1_1 },
                       { RW, uint8, sizeof (UNS8), (void*)&test_1_test_1_2 },
                       { RW, uint8, sizeof (UNS8), (void*)&test_1_test_1_3 },
                       { RW, uint8, sizeof (UNS8), (void*)&test_1_test_1_4 }
                     };

/* index 0x2006 :   Mapped variable test_2 */
                    UNS8 Master_highestSubIndex_obj2006 = 4; /* number of subindex - 1*/
                    subindex Master_Index2006[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2006 },
                       { RW, uint8, sizeof (UNS8), (void*)&test_2_test_2_1 },
                       { RW, uint8, sizeof (UNS8), (void*)&test_2_test_2_2 },
                       { RW, uint8, sizeof (UNS8), (void*)&test_2_test_2_3 },
                       { RW, uint8, sizeof (UNS8), (void*)&test_2_test_2_4 }
                     };

/* index 0x2007 :   Mapped variable test_3 */
                    UNS8 Master_highestSubIndex_obj2007 = 4; /* number of subindex - 1*/
                    subindex Master_Index2007[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2007 },
                       { RW, uint8, sizeof (UNS8), (void*)&test_3_test_3_1 },
                       { RW, uint8, sizeof (UNS8), (void*)&test_3_test_3_2 },
                       { RW, uint8, sizeof (UNS8), (void*)&test_3_test_3_3 },
                       { RW, uint8, sizeof (UNS8), (void*)&test_3_test_3_4 }
                     };

/* index 0x2008 :   Mapped variable test_4 */
                    UNS8 Master_highestSubIndex_obj2008 = 4; /* number of subindex - 1*/
                    subindex Master_Index2008[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2008 },
                       { RW, uint8, sizeof (UNS8), (void*)&test_4_test_4_1 },
                       { RW, uint8, sizeof (UNS8), (void*)&test_4_test_4_2 },
                       { RW, uint8, sizeof (UNS8), (void*)&test_4_test_4_3 },
                       { RW, uint8, sizeof (UNS8), (void*)&test_4_test_4_4 }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Master_objdict[] = 
{
  { (subindex*)Master_Index1000,sizeof(Master_Index1000)/sizeof(Master_Index1000[0]), 0x1000},
  { (subindex*)Master_Index1001,sizeof(Master_Index1001)/sizeof(Master_Index1001[0]), 0x1001},
  { (subindex*)Master_Index1017,sizeof(Master_Index1017)/sizeof(Master_Index1017[0]), 0x1017},
  { (subindex*)Master_Index1018,sizeof(Master_Index1018)/sizeof(Master_Index1018[0]), 0x1018},
  { (subindex*)Master_Index1280,sizeof(Master_Index1280)/sizeof(Master_Index1280[0]), 0x1280},
  { (subindex*)Master_Index1400,sizeof(Master_Index1400)/sizeof(Master_Index1400[0]), 0x1400},
  { (subindex*)Master_Index1401,sizeof(Master_Index1401)/sizeof(Master_Index1401[0]), 0x1401},
  { (subindex*)Master_Index1402,sizeof(Master_Index1402)/sizeof(Master_Index1402[0]), 0x1402},
  { (subindex*)Master_Index1403,sizeof(Master_Index1403)/sizeof(Master_Index1403[0]), 0x1403},
  { (subindex*)Master_Index1404,sizeof(Master_Index1404)/sizeof(Master_Index1404[0]), 0x1404},
  { (subindex*)Master_Index1405,sizeof(Master_Index1405)/sizeof(Master_Index1405[0]), 0x1405},
  { (subindex*)Master_Index1406,sizeof(Master_Index1406)/sizeof(Master_Index1406[0]), 0x1406},
  { (subindex*)Master_Index1407,sizeof(Master_Index1407)/sizeof(Master_Index1407[0]), 0x1407},
  { (subindex*)Master_Index1408,sizeof(Master_Index1408)/sizeof(Master_Index1408[0]), 0x1408},
  { (subindex*)Master_Index1409,sizeof(Master_Index1409)/sizeof(Master_Index1409[0]), 0x1409},
  { (subindex*)Master_Index140A,sizeof(Master_Index140A)/sizeof(Master_Index140A[0]), 0x140A},
  { (subindex*)Master_Index1600,sizeof(Master_Index1600)/sizeof(Master_Index1600[0]), 0x1600},
  { (subindex*)Master_Index1601,sizeof(Master_Index1601)/sizeof(Master_Index1601[0]), 0x1601},
  { (subindex*)Master_Index1602,sizeof(Master_Index1602)/sizeof(Master_Index1602[0]), 0x1602},
  { (subindex*)Master_Index1603,sizeof(Master_Index1603)/sizeof(Master_Index1603[0]), 0x1603},
  { (subindex*)Master_Index1604,sizeof(Master_Index1604)/sizeof(Master_Index1604[0]), 0x1604},
  { (subindex*)Master_Index1605,sizeof(Master_Index1605)/sizeof(Master_Index1605[0]), 0x1605},
  { (subindex*)Master_Index1606,sizeof(Master_Index1606)/sizeof(Master_Index1606[0]), 0x1606},
  { (subindex*)Master_Index1607,sizeof(Master_Index1607)/sizeof(Master_Index1607[0]), 0x1607},
  { (subindex*)Master_Index1608,sizeof(Master_Index1608)/sizeof(Master_Index1608[0]), 0x1608},
  { (subindex*)Master_Index1609,sizeof(Master_Index1609)/sizeof(Master_Index1609[0]), 0x1609},
  { (subindex*)Master_Index160A,sizeof(Master_Index160A)/sizeof(Master_Index160A[0]), 0x160A},
  { (subindex*)Master_Index2000,sizeof(Master_Index2000)/sizeof(Master_Index2000[0]), 0x2000},
  { (subindex*)Master_Index2001,sizeof(Master_Index2001)/sizeof(Master_Index2001[0]), 0x2001},
  { (subindex*)Master_Index2002,sizeof(Master_Index2002)/sizeof(Master_Index2002[0]), 0x2002},
  { (subindex*)Master_Index2003,sizeof(Master_Index2003)/sizeof(Master_Index2003[0]), 0x2003},
  { (subindex*)Master_Index2004,sizeof(Master_Index2004)/sizeof(Master_Index2004[0]), 0x2004},
  { (subindex*)Master_Index2005,sizeof(Master_Index2005)/sizeof(Master_Index2005[0]), 0x2005},
  { (subindex*)Master_Index2006,sizeof(Master_Index2006)/sizeof(Master_Index2006[0]), 0x2006},
  { (subindex*)Master_Index2007,sizeof(Master_Index2007)/sizeof(Master_Index2007[0]), 0x2007},
  { (subindex*)Master_Index2008,sizeof(Master_Index2008)/sizeof(Master_Index2008[0]), 0x2008},
};

const indextable * Master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1017: i = 2;*callbacks = Master_Index1017_callbacks; break;
		case 0x1018: i = 3;break;
		case 0x1280: i = 4;break;
		case 0x1400: i = 5;break;
		case 0x1401: i = 6;break;
		case 0x1402: i = 7;break;
		case 0x1403: i = 8;break;
		case 0x1404: i = 9;break;
		case 0x1405: i = 10;break;
		case 0x1406: i = 11;break;
		case 0x1407: i = 12;break;
		case 0x1408: i = 13;break;
		case 0x1409: i = 14;break;
		case 0x140A: i = 15;break;
		case 0x1600: i = 16;break;
		case 0x1601: i = 17;break;
		case 0x1602: i = 18;break;
		case 0x1603: i = 19;break;
		case 0x1604: i = 20;break;
		case 0x1605: i = 21;break;
		case 0x1606: i = 22;break;
		case 0x1607: i = 23;break;
		case 0x1608: i = 24;break;
		case 0x1609: i = 25;break;
		case 0x160A: i = 26;break;
		case 0x2000: i = 27;break;
		case 0x2001: i = 28;break;
		case 0x2002: i = 29;break;
		case 0x2003: i = 30;break;
		case 0x2004: i = 31;break;
		case 0x2005: i = 32;break;
		case 0x2006: i = 33;break;
		case 0x2007: i = 34;break;
		case 0x2008: i = 35;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &Master_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Master_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index Master_firstIndex = {
  0, /* SDO_SVR */
  4, /* SDO_CLT */
  5, /* PDO_RCV */
  16, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index Master_lastIndex = {
  0, /* SDO_SVR */
  4, /* SDO_CLT */
  15, /* PDO_RCV */
  26, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 Master_ObjdictSize = sizeof(Master_objdict)/sizeof(Master_objdict[0]); 

CO_Data Master_Data = CANOPEN_NODE_DATA_INITIALIZER(Master);

